/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsProgramSlugRouteImport } from './routes/programs.$programSlug'
import { Route as SpecialisationsIndexRouteImport } from './routes/specialisations.index'
import { Route as SpecialisationsSpecialisationSlugRouteImport } from './routes/specialisations.$specialisationSlug'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClaimsRouteImport } from './routes/_authenticated/admin.claims'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminOfferingSpecialisationsRouteImport } from './routes/_authenticated/admin.offering-specialisations'
import { Route as AuthenticatedAdminOfferingsRouteImport } from './routes/_authenticated/admin.offerings'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin.programs'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSpecialisationsRouteImport } from './routes/_authenticated/admin.specialisations'
import { Route as AuthenticatedAdminUniversitiesRouteImport } from './routes/_authenticated/admin.universities'
import { Route as UniversitiesUniversitySlugIndexRouteImport } from './routes/universities.$universitySlug.index'
import { Route as UniversitiesUniversitySlugProgramSlugRouteImport } from './routes/universities.$universitySlug.$programSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramSlugRoute = ProgramsProgramSlugRouteImport.update({
  id: '/programs/$programSlug',
  path: '/programs/$programSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialisationsIndexRoute = SpecialisationsIndexRouteImport.update({
  id: '/specialisations/',
  path: '/specialisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialisationsSpecialisationSlugRoute =
  SpecialisationsSpecialisationSlugRouteImport.update({
    id: '/specialisations/$specialisationSlug',
    path: '/specialisations/$specialisationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClaimsRoute =
  AuthenticatedAdminClaimsRouteImport.update({
    id: '/claims',
    path: '/claims',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOfferingSpecialisationsRoute =
  AuthenticatedAdminOfferingSpecialisationsRouteImport.update({
    id: '/offering-specialisations',
    path: '/offering-specialisations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOfferingsRoute =
  AuthenticatedAdminOfferingsRouteImport.update({
    id: '/offerings',
    path: '/offerings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpecialisationsRoute =
  AuthenticatedAdminSpecialisationsRouteImport.update({
    id: '/specialisations',
    path: '/specialisations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUniversitiesRoute =
  AuthenticatedAdminUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const UniversitiesUniversitySlugIndexRoute =
  UniversitiesUniversitySlugIndexRouteImport.update({
    id: '/universities/$universitySlug/',
    path: '/universities/$universitySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversitiesUniversitySlugProgramSlugRoute =
  UniversitiesUniversitySlugProgramSlugRouteImport.update({
    id: '/universities/$universitySlug/$programSlug',
    path: '/universities/$universitySlug/$programSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/finder': typeof FinderRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/specialisations/$specialisationSlug': typeof SpecialisationsSpecialisationSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/specialisations/': typeof SpecialisationsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/admin/claims': typeof AuthenticatedAdminClaimsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/offering-specialisations': typeof AuthenticatedAdminOfferingSpecialisationsRoute
  '/admin/offerings': typeof AuthenticatedAdminOfferingsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/specialisations': typeof AuthenticatedAdminSpecialisationsRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/universities/$universitySlug/$programSlug': typeof UniversitiesUniversitySlugProgramSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/universities/$universitySlug/': typeof UniversitiesUniversitySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/finder': typeof FinderRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/specialisations/$specialisationSlug': typeof SpecialisationsSpecialisationSlugRoute
  '/programs': typeof ProgramsIndexRoute
  '/specialisations': typeof SpecialisationsIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/admin/claims': typeof AuthenticatedAdminClaimsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/offering-specialisations': typeof AuthenticatedAdminOfferingSpecialisationsRoute
  '/admin/offerings': typeof AuthenticatedAdminOfferingsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/specialisations': typeof AuthenticatedAdminSpecialisationsRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/universities/$universitySlug/$programSlug': typeof UniversitiesUniversitySlugProgramSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/universities/$universitySlug': typeof UniversitiesUniversitySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/finder': typeof FinderRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/specialisations/$specialisationSlug': typeof SpecialisationsSpecialisationSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/specialisations/': typeof SpecialisationsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/_authenticated/admin/claims': typeof AuthenticatedAdminClaimsRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/offering-specialisations': typeof AuthenticatedAdminOfferingSpecialisationsRoute
  '/_authenticated/admin/offerings': typeof AuthenticatedAdminOfferingsRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/specialisations': typeof AuthenticatedAdminSpecialisationsRoute
  '/_authenticated/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/universities/$universitySlug/$programSlug': typeof UniversitiesUniversitySlugProgramSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/universities/$universitySlug/': typeof UniversitiesUniversitySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/finder'
    | '/methodology'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/programs/$programSlug'
    | '/specialisations/$specialisationSlug'
    | '/programs/'
    | '/specialisations/'
    | '/universities/'
    | '/admin/claims'
    | '/admin/leads'
    | '/admin/offering-specialisations'
    | '/admin/offerings'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/specialisations'
    | '/admin/universities'
    | '/universities/$universitySlug/$programSlug'
    | '/admin/'
    | '/universities/$universitySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/finder'
    | '/methodology'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/programs/$programSlug'
    | '/specialisations/$specialisationSlug'
    | '/programs'
    | '/specialisations'
    | '/universities'
    | '/admin/claims'
    | '/admin/leads'
    | '/admin/offering-specialisations'
    | '/admin/offerings'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/specialisations'
    | '/admin/universities'
    | '/universities/$universitySlug/$programSlug'
    | '/admin'
    | '/universities/$universitySlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/finder'
    | '/methodology'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/programs/$programSlug'
    | '/specialisations/$specialisationSlug'
    | '/programs/'
    | '/specialisations/'
    | '/universities/'
    | '/_authenticated/admin/claims'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/offering-specialisations'
    | '/_authenticated/admin/offerings'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/specialisations'
    | '/_authenticated/admin/universities'
    | '/universities/$universitySlug/$programSlug'
    | '/_authenticated/admin/'
    | '/universities/$universitySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FinderRoute: typeof FinderRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ProgramsProgramSlugRoute: typeof ProgramsProgramSlugRoute
  SpecialisationsSpecialisationSlugRoute: typeof SpecialisationsSpecialisationSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  SpecialisationsIndexRoute: typeof SpecialisationsIndexRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  UniversitiesUniversitySlugProgramSlugRoute: typeof UniversitiesUniversitySlugProgramSlugRoute
  UniversitiesUniversitySlugIndexRoute: typeof UniversitiesUniversitySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programSlug': {
      id: '/programs/$programSlug'
      path: '/programs/$programSlug'
      fullPath: '/programs/$programSlug'
      preLoaderRoute: typeof ProgramsProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialisations/': {
      id: '/specialisations/'
      path: '/specialisations'
      fullPath: '/specialisations/'
      preLoaderRoute: typeof SpecialisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialisations/$specialisationSlug': {
      id: '/specialisations/$specialisationSlug'
      path: '/specialisations/$specialisationSlug'
      fullPath: '/specialisations/$specialisationSlug'
      preLoaderRoute: typeof SpecialisationsSpecialisationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/universities'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/claims': {
      id: '/_authenticated/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AuthenticatedAdminClaimsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offering-specialisations': {
      id: '/_authenticated/admin/offering-specialisations'
      path: '/offering-specialisations'
      fullPath: '/admin/offering-specialisations'
      preLoaderRoute: typeof AuthenticatedAdminOfferingSpecialisationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offerings': {
      id: '/_authenticated/admin/offerings'
      path: '/offerings'
      fullPath: '/admin/offerings'
      preLoaderRoute: typeof AuthenticatedAdminOfferingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/specialisations': {
      id: '/_authenticated/admin/specialisations'
      path: '/specialisations'
      fullPath: '/admin/specialisations'
      preLoaderRoute: typeof AuthenticatedAdminSpecialisationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities': {
      id: '/_authenticated/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/universities/$universitySlug/': {
      id: '/universities/$universitySlug/'
      path: '/universities/$universitySlug'
      fullPath: '/universities/$universitySlug/'
      preLoaderRoute: typeof UniversitiesUniversitySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$universitySlug/$programSlug': {
      id: '/universities/$universitySlug/$programSlug'
      path: '/universities/$universitySlug/$programSlug'
      fullPath: '/universities/$universitySlug/$programSlug'
      preLoaderRoute: typeof UniversitiesUniversitySlugProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClaimsRoute: typeof AuthenticatedAdminClaimsRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminOfferingSpecialisationsRoute: typeof AuthenticatedAdminOfferingSpecialisationsRoute
  AuthenticatedAdminOfferingsRoute: typeof AuthenticatedAdminOfferingsRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSpecialisationsRoute: typeof AuthenticatedAdminSpecialisationsRoute
  AuthenticatedAdminUniversitiesRoute: typeof AuthenticatedAdminUniversitiesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClaimsRoute: AuthenticatedAdminClaimsRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminOfferingSpecialisationsRoute:
    AuthenticatedAdminOfferingSpecialisationsRoute,
  AuthenticatedAdminOfferingsRoute: AuthenticatedAdminOfferingsRoute,
  AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSpecialisationsRoute:
    AuthenticatedAdminSpecialisationsRoute,
  AuthenticatedAdminUniversitiesRoute: AuthenticatedAdminUniversitiesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FinderRoute: FinderRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ProgramsProgramSlugRoute: ProgramsProgramSlugRoute,
  SpecialisationsSpecialisationSlugRoute:
    SpecialisationsSpecialisationSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  SpecialisationsIndexRoute: SpecialisationsIndexRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  UniversitiesUniversitySlugProgramSlugRoute:
    UniversitiesUniversitySlugProgramSlugRoute,
  UniversitiesUniversitySlugIndexRoute: UniversitiesUniversitySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
