/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsProgramSlugRouteImport } from './routes/programs.$programSlug'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as UniversitiesUniversitySlugIndexRouteImport } from './routes/universities.$universitySlug.index'
import { Route as UniversitiesUniversitySlugProgramSlugRouteImport } from './routes/universities.$universitySlug.$programSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramSlugRoute = ProgramsProgramSlugRouteImport.update({
  id: '/programs/$programSlug',
  path: '/programs/$programSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesUniversitySlugIndexRoute =
  UniversitiesUniversitySlugIndexRouteImport.update({
    id: '/universities/$universitySlug/',
    path: '/universities/$universitySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversitiesUniversitySlugProgramSlugRoute =
  UniversitiesUniversitySlugProgramSlugRouteImport.update({
    id: '/universities/$universitySlug/$programSlug',
    path: '/universities/$universitySlug/$programSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/universities/$universitySlug/$programSlug': typeof UniversitiesUniversitySlugProgramSlugRoute
  '/universities/$universitySlug/': typeof UniversitiesUniversitySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/programs': typeof ProgramsIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/universities/$universitySlug/$programSlug': typeof UniversitiesUniversitySlugProgramSlugRoute
  '/universities/$universitySlug': typeof UniversitiesUniversitySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/universities/$universitySlug/$programSlug': typeof UniversitiesUniversitySlugProgramSlugRoute
  '/universities/$universitySlug/': typeof UniversitiesUniversitySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/sitemap.xml'
    | '/admin'
    | '/programs/$programSlug'
    | '/programs/'
    | '/universities/'
    | '/universities/$universitySlug/$programSlug'
    | '/universities/$universitySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/sitemap.xml'
    | '/admin'
    | '/programs/$programSlug'
    | '/programs'
    | '/universities'
    | '/universities/$universitySlug/$programSlug'
    | '/universities/$universitySlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/programs/$programSlug'
    | '/programs/'
    | '/universities/'
    | '/universities/$universitySlug/$programSlug'
    | '/universities/$universitySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProgramsProgramSlugRoute: typeof ProgramsProgramSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  UniversitiesUniversitySlugProgramSlugRoute: typeof UniversitiesUniversitySlugProgramSlugRoute
  UniversitiesUniversitySlugIndexRoute: typeof UniversitiesUniversitySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programSlug': {
      id: '/programs/$programSlug'
      path: '/programs/$programSlug'
      fullPath: '/programs/$programSlug'
      preLoaderRoute: typeof ProgramsProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/universities'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$universitySlug/': {
      id: '/universities/$universitySlug/'
      path: '/universities/$universitySlug'
      fullPath: '/universities/$universitySlug/'
      preLoaderRoute: typeof UniversitiesUniversitySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$universitySlug/$programSlug': {
      id: '/universities/$universitySlug/$programSlug'
      path: '/universities/$universitySlug/$programSlug'
      fullPath: '/universities/$universitySlug/$programSlug'
      preLoaderRoute: typeof UniversitiesUniversitySlugProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProgramsProgramSlugRoute: ProgramsProgramSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  UniversitiesUniversitySlugProgramSlugRoute:
    UniversitiesUniversitySlugProgramSlugRoute,
  UniversitiesUniversitySlugIndexRoute: UniversitiesUniversitySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
